### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by zxdong262** [electerm/electerm-web#4]
### What feature you'd like to see or proposal(期望什么新功能/特性或者建议)

- [ ] Bundled pack releases
- [ ] Update check
- [ ] Docker image
- [ ] Mongodb db wrappper extension
- [ ] Multi user support
- [ ] Custom login extension
- [ ] Mobile support
- [ ] Verify in multi OS, mac, linux, windows, arm
- [ ] Fix ShowItemInFolder function
- [ ] Fix auto login UI
- [ ] Demo mode support

**Comment by furriest** [comment]
Customizable user interface (enabling and disabling parts of the interface for different users).
For example, it would be useful for some user to disable almost everything and leave only the pre-configured tabs, without the ability to add another tab or open a menu.
